update_schedule:
  name: Update Schedule
  description: Update the optimization schedule with new parameters
  fields:
    home_size:
      name: Home Size
      description: Square footage of the home
      required: false
      example: 2000
      selector:
        number:
          min: 500
          max: 10000
          step: 100
          unit_of_measurement: "sq ft"
    savings_level:
      name: Savings Level
      description: Optimization aggressiveness (1=Low, 2=Medium, 3=High)
      required: false
      example: 2
      selector:
        select:
          options:
            - label: "Low (2°F offset)"
              value: "1"
            - label: "Medium (6°F offset)"
              value: "2"
            - label: "High (12°F offset)"
              value: "3"
    time_away:
      name: Away Time
      description: Time when you leave home (HH:MM format)
      required: false
      example: "08:00"
      selector:
        time:
    time_home:
      name: Home Time
      description: Time when you return home (HH:MM format)
      required: false
      example: "17:00"
      selector:
        time:

force_optimization:
  name: Force Optimization
  description: Force an immediate optimization calculation

update_rates:
  name: Update Learning Rates
  description: Update the heat-up and cool-down learning rates
  fields:
    heat_up_rate:
      name: Heat Up Rate
      description: Temperature rise per 30 minutes when heating/AC off
      required: true
      example: 0.5535
      selector:
        number:
          min: 0.1
          max: 2.0
          step: 0.0001
          mode: box
          unit_of_measurement: "°F/30min"
    cool_down_rate:
      name: Cool Down Rate
      description: Temperature drop per 30 minutes when cooling/AC on
      required: true
      example: 1.9335
      selector:
        number:
          min: 0.5
          max: 4.0
          step: 0.0001
          mode: box
          unit_of_measurement: "°F/30min"